# -*- coding: utf-8 -*-
"""generate_narrative.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ohWxdP7oWuvquIdBSOKnuu86_trgPsNo
"""



import json
import os
from pathlib import Path

from google import genai
from google.genai import types


# ============================================================
# OFFLINE FALLBACK
# ============================================================

def generate_scr_narrative_offline(findings: dict) -> dict:
    """
    Deterministic fallback that generates the SCR narrative
    directly from findings.json without using Gemini.
    """

    cleaned_revenue = findings["cleaned_total_revenue_inr"]
    duplicate_delta = findings["duplicate_reconciliation_delta_inr"]

    cod_rate = findings["return_rate_by_payment"]["COD"]

    risk_payment = findings["highest_risk_segment"]["payment_method"]
    risk_tier = findings["highest_risk_segment"]["city_tier"]
    risk_rate = findings["highest_risk_segment"]["return_rate_pct"]

    peak_month = findings["true_peak_month"]["month"]
    peak_revenue = findings["true_peak_month"]["revenue_inr"]

    month_names = {
        "01": "January",
        "02": "February",
        "03": "March",
        "04": "April",
        "05": "May",
        "06": "June",
        "07": "July",
        "08": "August",
        "09": "September",
        "10": "October",
        "11": "November",
        "12": "December"
    }

    peak_month_name = month_names[peak_month[-2:]]

    narrative = f"""Situation

The business recorded cleaned total revenue of {cleaned_revenue:,.2f} INR after a duplicate-driven reconciliation delta of {duplicate_delta:,.2f} INR. The validated peak month was {peak_month_name}, with revenue of {peak_revenue:,.2f} INR.

Complication

COD has a return rate of {cod_rate:.1f}%. The highest-risk segment is {risk_payment} in Tier-{risk_tier}, where the return rate is {risk_rate:.1f}%.

Resolution

Regional operations and finance teams should use the cleaned revenue as the reporting baseline, monitor COD returns closely, and focus operational review on the identified Tier-{risk_tier} segment while using {peak_month_name} as the validated peak-month reference.
"""

    return {
        "status": "success",
        "narrative": narrative,
        "tokens": None
    }


# ============================================================
# GEMINI NARRATIVE GENERATOR
# ============================================================

def generate_scr_narrative(findings: dict) -> dict:
    """
    Generate the SCR narrative using Gemini when an API key exists.
    Falls back to the deterministic offline function on failure.
    """

    # Your Gemini API key environment variable is named SG_api_key.
    api_key = os.getenv("SG_api_key")

    # No API key: immediately use the deterministic offline path.
    if not api_key:
        print("SG_api_key not found.")
        print("Using deterministic offline fallback.")
        return generate_scr_narrative_offline(findings)

    try:
        client = genai.Client(api_key=api_key)

        # Temperature 0.0 is intentional because this is a factual
        # business report, not creative writing, so deterministic output
        # is preferred.
        system_instruction = """
You are a senior data analyst writing for Mamaearth's regional ops
and finance heads.

Write the narrative using exactly three labeled sections, in this order:

Situation
Complication
Resolution

Use ONLY the supplied findings.

Every number in the output must come from the supplied findings
and must appear with the same value. Do not invent, estimate,
calculate, round, or introduce any new statistics.

Do not introduce additional percentages, revenue figures,
ratios, order counts, dates, or other numerical values.

Preserve the supplied numerical values accurately.

Keep the narrative concise, factual, and suitable for regional
operations and finance leadership.
"""

        # The numbers are taken from the findings argument.
        # Nothing is hardcoded here.
        contents = f"""
Create the required Situation-Complication-Resolution business
narrative from these verified findings:

{json.dumps(findings, indent=2)}

Every number used in the narrative must come from these findings.
"""

        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=contents,
            config=types.GenerateContentConfig(
                system_instruction=system_instruction,
                temperature=0.0,
                max_output_tokens=500,
                http_options=types.HttpOptions(
                    timeout=30000
                )
            )
        )

        narrative = response.text

        # Try to obtain usage information when available.
        tokens = None

        if getattr(response, "usage_metadata", None):
            tokens = getattr(
                response.usage_metadata,
                "total_token_count",
                None
            )

        return {
            "status": "success",
            "narrative": narrative,
            "tokens": tokens
        }

    except Exception as err:
        print("Gemini API failed.")
        print(f"Reason: {err}")
        print("Using deterministic offline fallback.")

        return generate_scr_narrative_offline(findings)


# ============================================================
# TASK 5 NUMERIC CHECKER
# ============================================================

def check_narrative_numbers(narrative: str) -> bool:
    """
    Check that the required figures from the project brief
    appear in the generated narrative.
    """

    normalized = narrative.replace(",", "")

    checks = {
        "97,358.30 cleaned revenue": (
            "97358.30" in normalized or
            "97358.3" in normalized
        ),

        "44.4 COD return rate": (
            "44.4" in normalized
        ),

        "54.5 COD + Tier-2 risk rate": (
            "54.5" in normalized
        ),

        "2,501.90 reconciliation delta": (
            "2501.90" in normalized or
            "2501.9" in normalized
        ),

        "March + 20,318.90 peak revenue": (
            "March" in narrative and
            (
                "20318.90" in normalized or
                "20318.9" in normalized
            )
        )
    }

    all_passed = True

    print("\nNumeric Accuracy Checker")
    print("=" * 60)

    for label, passed in checks.items():

        if passed:
            print(f"PASS - {label}")
        else:
            print(f"FAIL - {label}")
            all_passed = False

    print("=" * 60)

    if all_passed:
        print("NUMERIC CHECK: PASS")
    else:
        print("NUMERIC CHECK: FAIL")

    return all_passed


# ============================================================
# MAIN RUNNER
# ============================================================

def main():


    findings_path = Path("/content/findings.json")

    # Save the generated narrative directly into /content.
    sample_output_path = Path("/content/sample_output.txt")

    # Check that findings.json exists before trying to open it.
    if not findings_path.exists():
        raise FileNotFoundError(
            f"Could not find {findings_path}. "
            "Upload findings.json to the Colab notebook first."
        )

    print("Loading findings from:")
    print(findings_path)

    with open(findings_path, "r", encoding="utf-8") as file:
        findings = json.load(file)

    print("findings.json loaded successfully.")

    print("\nStarting narrative generation...")
    result = generate_scr_narrative(findings)

    print("\nNarrative generation result")
    print("=" * 60)
    print("Status:", result["status"])
    print("Tokens:", result.get("tokens"))

    print("\nGenerated narrative:")
    print("-" * 60)
    print(result["narrative"])

    # Save the actual generated narrative.
    with open(sample_output_path, "w", encoding="utf-8") as file:
        file.write(result["narrative"])

    print("\nSaved:")
    print(sample_output_path)

    # Check the generated narrative.
    generated_check = check_narrative_numbers(
        result["narrative"]
    )

    # Check the saved sample exactly as it was written.
    with open(sample_output_path, "r", encoding="utf-8") as file:
        saved_narrative = file.read()

    print("\nChecker against /content/sample_output.txt")

    saved_check = check_narrative_numbers(
        saved_narrative
    )

    print("\nFinal Task 5 Result")
    print("=" * 60)

    if generated_check and saved_check:
        print("PASS - All required numeric figures are present.")
    else:
        print("FAIL - One or more required numeric figures are missing.")


if __name__ == "__main__":
    main()