# -*- coding: utf-8 -*-
"""clean_and_eda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ymoxgJpQw1UmNpP-FIEsJyj9hEFEi6yz
"""

import pandas as pd
import matplotlib.pyplot as plt

#Loading all 3 CSVs and inspecting the orders
products = pd.read_csv("Products.csv")
customers = pd.read_csv("Customers.csv")
orders = pd.read_csv("Orders.csv")

print(orders.shape)

#Distinct raw values in payment_method
print(orders['payment_method'].unique())

#Standardlize payment_method casing
orders['payment_method']=orders['payment_method'].str.strip().str.upper()

print(orders.head(10))

# Detect duplicates
natural_key = [
    "customer_id",
    "product_id",
    "order_date",
    "quantity",
    "discount_pct",
    "payment_method",
    "rating",
    "returned"
]


duplicates = orders.duplicated(subset=natural_key, keep="first")
dropped_order_ids = orders.loc[duplicates, "order_id"]

print(dropped_order_ids.tolist())

# Drop duplicates, keeping the first occurrence
orders = orders.drop_duplicates(subset=natural_key, keep="first")

#print(orders.tail(5))
print(orders.shape)

#Handling Missing Values from discount_pct and rating
orders['discount_pct']=orders['discount_pct'].fillna(0)
orders_rating_median = orders['rating'].median()
print(orders_rating_median)
orders['rating']=orders['rating'].fillna(orders['rating'].median())

# To Verify NO Null Values Present inside discount_pct and rating
orders_clean = orders.copy()

print("Missing values:")
print(orders_clean[["discount_pct", "rating"]].isnull().sum())

# Merge cleaned orders with products and customers
orders_clean = orders.merge(
    products[["product_id", "price"]],
    on="product_id",
    how="left"
).merge(
    customers[["customer_id","city_tier"]],
    on="customer_id",
    how="left"
)

# Calculate order value
orders_clean["order_value"] = (
    orders_clean["quantity"]
    * orders_clean["price"]
    * (1 - orders_clean["discount_pct"] / 100)
)

# Print total order value
clean_total = orders_clean["order_value"].sum()

print(f"Total order value across {len(orders_clean)} cleaned rows: ₹{clean_total:.2f}")

orders_raw = pd.read_csv("Orders.csv")
# Identify the 5 duplicate rows that were dropped
natural_key = [
    "customer_id",
    "product_id",
    "order_date",
    "quantity",
    "discount_pct",
    "payment_method",
    "rating",
    "returned"
]

duplicate_rows = orders_raw[
    orders_raw.duplicated(subset=natural_key, keep="first")
].copy()

# Merge dropped rows with products to get price
duplicate_rows = duplicate_rows.merge(
    products[["product_id", "price"]],
    on="product_id",
    how="left"
)

# Calculate their order values independently
duplicate_rows["order_value"] = (
    duplicate_rows["quantity"]
    * duplicate_rows["price"]
    * (1 - duplicate_rows["discount_pct"] / 100)
)

dropped_total = duplicate_rows["order_value"].sum()

print(f"Order value of 5 dropped duplicate rows: ₹{dropped_total:.2f}")

print(
    "Reconciliation: The cleaned total order value is ₹97,358.30, "
    "compared with the raw total of ₹99,860.20, resulting in a "
    "difference of ₹2,501.90. This difference is fully attributable "
    "to the removal of 5 duplicate orders, whose combined order value "
    "is ₹2,501.90. The discount and rating imputations do not change "
    "the order value total: missing discounts were treated as 0%, and "
    "rating is not used in the order value calculation."
)

# Calculate Q1, Q3, IQR, lower and upper bounds
Q1 = orders_clean["quantity"].quantile(0.25)
Q3 = orders_clean["quantity"].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower bound:", lower)
print("Upper bound:", upper)

orders_clean["is_outlier"] = (
    (orders_clean["quantity"] < lower) |
    (orders_clean["quantity"] > upper))
outliers = orders_clean[orders_clean["is_outlier"]]

print(outliers[["order_id", "quantity"]])

print("Hypothesis: COD has a higher return rate than CARD and UPI.")

return_rates = orders_clean.groupby("payment_method")["returned"].agg(
    ["count", "mean"]
)

print(return_rates)

print("\nReturn rates:")
for method, row in return_rates.iterrows():
    print(f"{method}: {row['mean'] * 100:.1f}%")

print("\nHypothesis: Confirmed")

# Return Rate Analysis by Payment Method and City Tier

segment_returns = (
    orders_clean
    .groupby(["payment_method", "city_tier"])["returned"]
    .agg(["count", "mean"])
)

print(segment_returns)

print("\nReturn rates by segment:")
for (payment_method, city_tier), row in segment_returns.iterrows():
    print(
        f"{payment_method} + {city_tier}: "
        f"{row['mean'] * 100:.1f}% ({int(row['count'])} orders)"
    )

print(
    "\nHighest-risk segment: COD + Tier-2 cities at 54.5%. "
    "COD return risk is not uniform across tiers: Tier-1 COD has "
    "a 37.5% return rate across 32 orders, compared with 54.5% "
    "across 22 Tier-2 COD orders."
)

# Correlation Analysis: Rating, Returns, Discount, and Quantity

columns = ["rating", "returned", "discount_pct", "quantity"]

correlation_matrix = orders_clean[columns].corr()

print("Correlation Matrix:")
print(correlation_matrix)

print("\nCorrelation Strength by Pair:")

pairs = [
    ("rating", "returned"),
    ("rating", "discount_pct"),
    ("rating", "quantity"),
    ("returned", "discount_pct"),
    ("returned", "quantity"),
    ("discount_pct", "quantity")
]

for col1, col2 in pairs:
    r = correlation_matrix.loc[col1, col2]

    if abs(r) < 0.2:
        strength = "negligible"
    elif abs(r) < 0.4:
        strength = "weak"
    elif abs(r) < 0.7:
        strength = "moderate"
    else:
        strength = "strong"

    print(f"{col1} vs {col2}: r = {r:.2f} → {strength}")

print(
    "\nHypothesis: Higher discounts reduce returns — Busted. "
    f"The correlation between discount_pct and returned is "
    f"{correlation_matrix.loc['discount_pct', 'returned']:.2f}, "
    "which falls in the negligible correlation band (|r| < 0.2)."
)

# Monthly Order Value Analysis: Impact of Quantity Outliers

# Convert order_date to datetime
orders_clean["order_date"] = pd.to_datetime(orders_clean["order_date"])

# Extract year-month
orders_clean["year_month"] = orders_clean["order_date"].dt.to_period("M")

# (1) Monthly total including outliers
monthly_with_outliers = (
    orders_clean
    .groupby("year_month")["order_value"]
    .sum()
)

print("Monthly order value including outliers:")
for month, value in monthly_with_outliers.items():
    print(f"{month}: ₹{value:.2f}")

# (2) Monthly total excluding outliers
monthly_without_outliers = (
    orders_clean[~orders_clean["is_outlier"]]
    .groupby("year_month")["order_value"]
    .sum()
)

print("\nMonthly order value excluding outliers:")
for month, value in monthly_without_outliers.items():
    print(f"{month}: ₹{value:.2f}")

# Identify highest months
highest_with_outliers = monthly_with_outliers.idxmax()
highest_without_outliers = monthly_without_outliers.idxmax()

print(
    f"\nIncluding outliers, January appears to be the highest month "
    f"({highest_with_outliers}: ₹{monthly_with_outliers.max():.2f})."
)

print(
    "January's apparent lead is an artifact of the two bulk orders "
    "landing in January: O0011 on 2026-01-28 and O0098 on 2026-01-10."
)

print(
    f"After excluding these two outlier orders, March is the genuine "
    f"peak month ({highest_without_outliers}: "
    f"₹{monthly_without_outliers.max():.2f})."
)

import json
from pathlib import Path
import pandas as pd


# ============================================================
# TASK 1 — Generate narrator/findings.json
# ============================================================

BASE_DIR = Path("/content")

# Your CSV files are currently directly in /content
customers = pd.read_csv(BASE_DIR / "Customers.csv")
products = pd.read_csv(BASE_DIR / "Products.csv")
orders_raw = pd.read_csv(BASE_DIR / "Orders.csv")


# Create narrator folder
NARRATOR_DIR = BASE_DIR / "narrator"
NARRATOR_DIR.mkdir(exist_ok=True)


# ============================================================
# Clean orders
# ============================================================

orders = orders_raw.copy()

natural_key = [
    "customer_id",
    "product_id",
    "order_date",
    "quantity",
    "discount_pct",
    "payment_method",
    "rating",
    "returned"
]

orders = orders.drop_duplicates(
    subset=natural_key
).copy()

orders["discount_pct"] = orders["discount_pct"].fillna(0)

orders["rating"] = orders["rating"].fillna(
    orders["rating"].median()
)

# Standardize payment method
orders["payment_method"] = (
    orders["payment_method"]
    .astype(str)
    .str.strip()
    .str.upper()
)


# ============================================================
# Cleaned revenue
# ============================================================

orders_clean = orders.merge(
    products[["product_id", "price"]],
    on="product_id",
    how="left"
)

orders_clean["order_value"] = (
    orders_clean["quantity"]
    * orders_clean["price"]
    * (1 - orders_clean["discount_pct"] / 100)
)

cleaned_total_revenue = orders_clean["order_value"].sum()


# ============================================================
# Raw revenue
# ============================================================

raw_revenue = orders_raw.merge(
    products[["product_id", "price"]],
    on="product_id",
    how="left"
)

raw_revenue["order_value"] = (
    raw_revenue["quantity"]
    * raw_revenue["price"]
    * (
        1
        - raw_revenue["discount_pct"].fillna(0) / 100
    )
)

raw_total_revenue = raw_revenue["order_value"].sum()


# ============================================================
# Duplicate reconciliation
# ============================================================

duplicate_mask = orders_raw.duplicated(
    subset=natural_key,
    keep="first"
)

duplicate_rows = orders_raw.loc[
    duplicate_mask
].copy()

duplicate_rows = duplicate_rows.merge(
    products[["product_id", "price"]],
    on="product_id",
    how="left"
)

duplicate_rows["order_value"] = (
    duplicate_rows["quantity"]
    * duplicate_rows["price"]
    * (
        1
        - duplicate_rows["discount_pct"].fillna(0) / 100
    )
)

duplicate_reconciliation_delta = (
    duplicate_rows["order_value"].sum()
)


# ============================================================
# Return rate by payment
# ============================================================

return_rate_by_payment = (
    orders_clean
    .groupby("payment_method")["returned"]
    .mean()
    * 100
)


# ============================================================
# Highest-risk segment
# ============================================================

segment_data = orders_clean.merge(
    customers[["customer_id", "city_tier"]],
    on="customer_id",
    how="left"
)

segment_returns = (
    segment_data
    .groupby(
        ["payment_method", "city_tier"]
    )["returned"]
    .mean()
    * 100
)

highest_risk_segment = segment_returns.idxmax()
highest_risk_rate = segment_returns.max()


# ============================================================
# Monthly revenue
# ============================================================

orders_clean["order_date"] = pd.to_datetime(
    orders_clean["order_date"]
)

orders_clean["month"] = (
    orders_clean["order_date"]
    .dt.to_period("M")
    .astype(str)
)

monthly_with_outliers = (
    orders_clean
    .groupby("month")["order_value"]
    .sum()
)


# ============================================================
# Quantity outliers
# ============================================================

q1 = orders_clean["quantity"].quantile(0.25)
q3 = orders_clean["quantity"].quantile(0.75)

iqr = q3 - q1

lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

outlier_mask = (
    (orders_clean["quantity"] < lower_bound)
    | (orders_clean["quantity"] > upper_bound)
)

monthly_without_outliers = (
    orders_clean.loc[~outlier_mask]
    .groupby("month")["order_value"]
    .sum()
)


# ============================================================
# Peak months
# ============================================================

true_peak_month = monthly_without_outliers.idxmax()
true_peak_revenue = monthly_without_outliers.max()

apparent_peak_month = monthly_with_outliers.idxmax()
apparent_peak_revenue = monthly_with_outliers.max()

corrected_apparent_peak_revenue = (
    monthly_without_outliers.loc[apparent_peak_month]
)


# ============================================================
# Create findings
# ============================================================

findings = {
    "cleaned_total_revenue_inr": round(
        cleaned_total_revenue, 2
    ),

    "raw_total_revenue_inr": round(
        raw_total_revenue, 2
    ),

    "duplicate_reconciliation_delta_inr": round(
        duplicate_reconciliation_delta, 2
    ),

    "return_rate_by_payment": {
        method: round(rate, 1)
        for method, rate
        in return_rate_by_payment.items()
    },

    "highest_risk_segment": {
        "payment_method": highest_risk_segment[0],
        "city_tier": int(highest_risk_segment[1]),
        "return_rate_pct": round(
            highest_risk_rate, 1
        )
    },

    "true_peak_month": {
        "month": str(true_peak_month),
        "revenue_inr": round(
            true_peak_revenue, 2
        )
    },

    "outlier_inflated_month": {
        "month": str(apparent_peak_month),
        "apparent_revenue_inr": round(
            apparent_peak_revenue, 2
        ),
        "corrected_revenue_inr": round(
            corrected_apparent_peak_revenue, 2
        )
    }
}


# ============================================================
# Validation
# ============================================================

assert set(return_rate_by_payment.index) == {
    "COD",
    "CARD",
    "UPI"
}, "Payment methods are not exactly COD, CARD and UPI."

assert round(
    cleaned_total_revenue
    + duplicate_reconciliation_delta,
    2
) == round(
    raw_total_revenue,
    2
), "Revenue reconciliation failed."


# ============================================================
# Write findings.json
# ============================================================

findings_path = NARRATOR_DIR / "findings.json"

with open(
    findings_path,
    "w",
    encoding="utf-8"
) as file:
    json.dump(
        findings,
        file,
        indent=4
    )


# ============================================================
# Display result
# ============================================================

print("=" * 60)
print("TASK 1 COMPLETE")
print("=" * 60)

print("\nFile created:")
print(findings_path)

print("\nGenerated findings.json:")
print(json.dumps(findings, indent=4))