# -*- coding: utf-8 -*-
"""visualize.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15k18N5V3Rl3Ozi4XqtrgHSQseoZUT1Im
"""

import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

# -----------------------------
# File paths
# -----------------------------
BASE_DIR = Path.cwd()
DATA_DIR = BASE_DIR
VIZ_DIR = BASE_DIR / "visualizations"

VIZ_DIR.mkdir(exist_ok=True)

# -----------------------------
# Load raw CSV files
# -----------------------------
orders = pd.read_csv(DATA_DIR / "Orders.csv")
products = pd.read_csv(DATA_DIR / "Products.csv")
customers = pd.read_csv(DATA_DIR / "Customers.csv")


orders_raw = orders.copy()

# -----------------------------
# Standardize payment method
# -----------------------------

orders["payment_method"] = (
    orders["payment_method"]
    .astype(str)
    .str.strip()
    .str.upper()
)

# -----------------------------
# Task 3: Remove duplicates
# -----------------------------
natural_key = [
    "customer_id",
    "product_id",
    "order_date",
    "quantity",
    "discount_pct",
    "payment_method",
    "rating",
    "returned"
]

orders = orders.drop_duplicates(
    subset=natural_key,
    keep="first"
).copy()


orders["discount_pct"] = orders["discount_pct"].fillna(0)

rating_median = orders["rating"].median()
orders["rating"] = orders["rating"].fillna(rating_median)

# -----------------------------
# Merge orders + products + customers
# -----------------------------
orders_clean = (
    orders
    .merge(
        products[["product_id", "price"]],
        on="product_id",
        how="left"
    )
    .merge(
        customers[["customer_id", "city_tier"]],
        on="customer_id",
        how="left"
    )
)

# -----------------------------
# Calculate order value
# -----------------------------
orders_clean["order_value"] = (
    orders_clean["quantity"]
    * orders_clean["price"]
    * (1 - orders_clean["discount_pct"] / 100)
)

# -----------------------------
# Task 6: Flag quantity outliers
# -----------------------------
Q1 = orders_clean["quantity"].quantile(0.25)
Q3 = orders_clean["quantity"].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

orders_clean["is_outlier"] = (
    (orders_clean["quantity"] < lower)
    | (orders_clean["quantity"] > upper)
)

# ============================================================
# 1. Return rate by cleaned payment method
# ============================================================

return_rates = (
    orders_clean
    .groupby("payment_method")["returned"]
    .mean()
    .sort_values(ascending=False)
)

assert set(return_rates.index) == {"COD", "CARD", "UPI"}, \
    f"Unexpected payment methods: {list(return_rates.index)}"

fig, ax = plt.subplots(figsize=(8, 5))

bars = ax.bar(
    return_rates.index,
    return_rates.values * 100
)

# Exact percentage on each bar
for bar, rate in zip(bars, return_rates.values * 100):
    ax.text(
        bar.get_x() + bar.get_width() / 2,
        bar.get_height(),
        f"{rate:.1f}%",
        ha="center",
        va="bottom"
    )

ax.set_xlabel("Payment Method")
ax.set_ylabel("Return Rate (%)")
ax.set_title("Return Rate by Payment Method")
ax.set_ylim(0, max(return_rates.values * 100) + 10)

plt.tight_layout()

fig.savefig(
    VIZ_DIR / "return_rate_by_payment.png",
    dpi=300,
    bbox_inches="tight"
)

plt.close(fig)


print("Cleaned return rates:")
print((return_rates * 100).round(1))

# ============================================================
# 2. Outlier-corrected monthly revenue trend
# ============================================================

orders_clean["order_date"] = pd.to_datetime(
    orders_clean["order_date"]
)

orders_clean["year_month"] = (
    orders_clean["order_date"]
    .dt.to_period("M")
)

monthly_revenue = (
    orders_clean[~orders_clean["is_outlier"]]
    .groupby("year_month")["order_value"]
    .sum()
)

peak_month = monthly_revenue.idxmax()
peak_value = monthly_revenue.max()

fig, ax = plt.subplots(figsize=(9, 5))

ax.plot(
    monthly_revenue.index.astype(str),
    monthly_revenue.values,
    marker="o"
)

ax.set_xlabel("Month")
ax.set_ylabel("Revenue (₹)")
ax.set_title(
    f"Monthly Revenue Trend — Peak: {peak_month}"
)

ax.tick_params(axis="x", rotation=45)

plt.tight_layout()

fig.savefig(
    VIZ_DIR / "monthly_revenue_trend.png",
    dpi=300,
    bbox_inches="tight"
)

plt.close(fig)

print("Visualizations generated successfully.")
print(f"Return-rate chart: {VIZ_DIR / 'return_rate_by_payment.png'}")
print(f"Monthly revenue chart: {VIZ_DIR / 'monthly_revenue_trend.png'}")
print(f"Actual revenue peak: {peak_month} — ₹{peak_value:.2f}")
